server:
  port: 8763
spring:
  application:
    name: eurekaclient
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh